package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ec.gob.snap.vuv.model.Act_Institucional;
import ec.gob.snap.vuv.service.Act_InstitucionalLocalServiceUtil;

/**
 * The extended model base implementation for the Act_Institucional service. Represents a row in the &quot;vuv_gpr_service_builder_Act_Institucional&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Act_InstitucionalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Act_InstitucionalImpl
 * @see ec.gob.snap.vuv.model.Act_Institucional
 * @generated
 */
public abstract class Act_InstitucionalBaseImpl
    extends Act_InstitucionalModelImpl implements Act_Institucional {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a act_ institucional model instance should use the {@link Act_Institucional} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Act_InstitucionalLocalServiceUtil.addAct_Institucional(this);
        } else {
            Act_InstitucionalLocalServiceUtil.updateAct_Institucional(this);
        }
    }
}
