package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ec.gob.snap.vuv.model.Centro;
import ec.gob.snap.vuv.service.CentroLocalServiceUtil;

/**
 * The extended model base implementation for the Centro service. Represents a row in the &quot;vuv_gpr_service_builder_Centro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CentroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CentroImpl
 * @see ec.gob.snap.vuv.model.Centro
 * @generated
 */
public abstract class CentroBaseImpl extends CentroModelImpl implements Centro {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a centro model instance should use the {@link Centro} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CentroLocalServiceUtil.addCentro(this);
        } else {
            CentroLocalServiceUtil.updateCentro(this);
        }
    }
}
