package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import ec.gob.snap.vuv.model.Centro;
import ec.gob.snap.vuv.model.CentroModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Centro service. Represents a row in the &quot;vuv_gpr_service_builder_Centro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ec.gob.snap.vuv.model.CentroModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CentroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CentroImpl
 * @see ec.gob.snap.vuv.model.Centro
 * @see ec.gob.snap.vuv.model.CentroModel
 * @generated
 */
public class CentroModelImpl extends BaseModelImpl<Centro>
    implements CentroModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a centro model instance should use the {@link ec.gob.snap.vuv.model.Centro} interface instead.
     */
    public static final String TABLE_NAME = "vuv_gpr_service_builder_Centro";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_centro", Types.BIGINT },
            { "id_GPR_centro", Types.BIGINT },
            { "content", Types.BIGINT },
            { "timeStamp", Types.TIMESTAMP },
            { "id_caso", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table vuv_gpr_service_builder_Centro (id_centro LONG not null primary key,id_GPR_centro LONG,content LONG,timeStamp DATE null,id_caso LONG)";
    public static final String TABLE_SQL_DROP = "drop table vuv_gpr_service_builder_Centro";
    public static final String ORDER_BY_JPQL = " ORDER BY centro.id_centro ASC";
    public static final String ORDER_BY_SQL = " ORDER BY vuv_gpr_service_builder_Centro.id_centro ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.ec.gob.snap.vuv.model.Centro"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.ec.gob.snap.vuv.model.Centro"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.ec.gob.snap.vuv.model.Centro"));
    private static ClassLoader _classLoader = Centro.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Centro.class };
    private long _id_centro;
    private long _id_GPR_centro;
    private long _content;
    private Date _timeStamp;
    private long _id_caso;
    private Centro _escapedModel;

    public CentroModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _id_centro;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId_centro(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id_centro;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Centro.class;
    }

    @Override
    public String getModelClassName() {
        return Centro.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id_centro", getId_centro());
        attributes.put("id_GPR_centro", getId_GPR_centro());
        attributes.put("content", getContent());
        attributes.put("timeStamp", getTimeStamp());
        attributes.put("id_caso", getId_caso());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id_centro = (Long) attributes.get("id_centro");

        if (id_centro != null) {
            setId_centro(id_centro);
        }

        Long id_GPR_centro = (Long) attributes.get("id_GPR_centro");

        if (id_GPR_centro != null) {
            setId_GPR_centro(id_GPR_centro);
        }

        Long content = (Long) attributes.get("content");

        if (content != null) {
            setContent(content);
        }

        Date timeStamp = (Date) attributes.get("timeStamp");

        if (timeStamp != null) {
            setTimeStamp(timeStamp);
        }

        Long id_caso = (Long) attributes.get("id_caso");

        if (id_caso != null) {
            setId_caso(id_caso);
        }
    }

    @Override
    public long getId_centro() {
        return _id_centro;
    }

    @Override
    public void setId_centro(long id_centro) {
        _id_centro = id_centro;
    }

    @Override
    public long getId_GPR_centro() {
        return _id_GPR_centro;
    }

    @Override
    public void setId_GPR_centro(long id_GPR_centro) {
        _id_GPR_centro = id_GPR_centro;
    }

    @Override
    public long getContent() {
        return _content;
    }

    @Override
    public void setContent(long content) {
        _content = content;
    }

    @Override
    public Date getTimeStamp() {
        return _timeStamp;
    }

    @Override
    public void setTimeStamp(Date timeStamp) {
        _timeStamp = timeStamp;
    }

    @Override
    public long getId_caso() {
        return _id_caso;
    }

    @Override
    public void setId_caso(long id_caso) {
        _id_caso = id_caso;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Centro.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Centro toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Centro) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        CentroImpl centroImpl = new CentroImpl();

        centroImpl.setId_centro(getId_centro());
        centroImpl.setId_GPR_centro(getId_GPR_centro());
        centroImpl.setContent(getContent());
        centroImpl.setTimeStamp(getTimeStamp());
        centroImpl.setId_caso(getId_caso());

        centroImpl.resetOriginalValues();

        return centroImpl;
    }

    @Override
    public int compareTo(Centro centro) {
        long primaryKey = centro.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Centro)) {
            return false;
        }

        Centro centro = (Centro) obj;

        long primaryKey = centro.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Centro> toCacheModel() {
        CentroCacheModel centroCacheModel = new CentroCacheModel();

        centroCacheModel.id_centro = getId_centro();

        centroCacheModel.id_GPR_centro = getId_GPR_centro();

        centroCacheModel.content = getContent();

        Date timeStamp = getTimeStamp();

        if (timeStamp != null) {
            centroCacheModel.timeStamp = timeStamp.getTime();
        } else {
            centroCacheModel.timeStamp = Long.MIN_VALUE;
        }

        centroCacheModel.id_caso = getId_caso();

        return centroCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{id_centro=");
        sb.append(getId_centro());
        sb.append(", id_GPR_centro=");
        sb.append(getId_GPR_centro());
        sb.append(", content=");
        sb.append(getContent());
        sb.append(", timeStamp=");
        sb.append(getTimeStamp());
        sb.append(", id_caso=");
        sb.append(getId_caso());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append("ec.gob.snap.vuv.model.Centro");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id_centro</column-name><column-value><![CDATA[");
        sb.append(getId_centro());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>id_GPR_centro</column-name><column-value><![CDATA[");
        sb.append(getId_GPR_centro());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>content</column-name><column-value><![CDATA[");
        sb.append(getContent());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>timeStamp</column-name><column-value><![CDATA[");
        sb.append(getTimeStamp());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>id_caso</column-name><column-value><![CDATA[");
        sb.append(getId_caso());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
