package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ec.gob.snap.vuv.model.Institucion;
import ec.gob.snap.vuv.service.InstitucionLocalServiceUtil;

/**
 * The extended model base implementation for the Institucion service. Represents a row in the &quot;vuv_gpr_service_builder_Institucion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InstitucionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InstitucionImpl
 * @see ec.gob.snap.vuv.model.Institucion
 * @generated
 */
public abstract class InstitucionBaseImpl extends InstitucionModelImpl
    implements Institucion {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a institucion model instance should use the {@link Institucion} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            InstitucionLocalServiceUtil.addInstitucion(this);
        } else {
            InstitucionLocalServiceUtil.updateInstitucion(this);
        }
    }
}
