package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import ec.gob.snap.vuv.model.Paso;
import ec.gob.snap.vuv.model.PasoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Paso service. Represents a row in the &quot;vuv_gpr_service_builder_Paso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ec.gob.snap.vuv.model.PasoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PasoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PasoImpl
 * @see ec.gob.snap.vuv.model.Paso
 * @see ec.gob.snap.vuv.model.PasoModel
 * @generated
 */
public class PasoModelImpl extends BaseModelImpl<Paso> implements PasoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a paso model instance should use the {@link ec.gob.snap.vuv.model.Paso} interface instead.
     */
    public static final String TABLE_NAME = "vuv_gpr_service_builder_Paso";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_paso", Types.BIGINT },
            { "id_GPR_paso", Types.BIGINT },
            { "content", Types.BIGINT },
            { "timeStamp", Types.TIMESTAMP },
            { "id_caso", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table vuv_gpr_service_builder_Paso (id_paso LONG not null primary key,id_GPR_paso LONG,content LONG,timeStamp DATE null,id_caso LONG)";
    public static final String TABLE_SQL_DROP = "drop table vuv_gpr_service_builder_Paso";
    public static final String ORDER_BY_JPQL = " ORDER BY paso.id_paso ASC";
    public static final String ORDER_BY_SQL = " ORDER BY vuv_gpr_service_builder_Paso.id_paso ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.ec.gob.snap.vuv.model.Paso"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.ec.gob.snap.vuv.model.Paso"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.ec.gob.snap.vuv.model.Paso"));
    private static ClassLoader _classLoader = Paso.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Paso.class };
    private long _id_paso;
    private long _id_GPR_paso;
    private long _content;
    private Date _timeStamp;
    private long _id_caso;
    private Paso _escapedModel;

    public PasoModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _id_paso;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId_paso(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id_paso;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Paso.class;
    }

    @Override
    public String getModelClassName() {
        return Paso.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id_paso", getId_paso());
        attributes.put("id_GPR_paso", getId_GPR_paso());
        attributes.put("content", getContent());
        attributes.put("timeStamp", getTimeStamp());
        attributes.put("id_caso", getId_caso());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id_paso = (Long) attributes.get("id_paso");

        if (id_paso != null) {
            setId_paso(id_paso);
        }

        Long id_GPR_paso = (Long) attributes.get("id_GPR_paso");

        if (id_GPR_paso != null) {
            setId_GPR_paso(id_GPR_paso);
        }

        Long content = (Long) attributes.get("content");

        if (content != null) {
            setContent(content);
        }

        Date timeStamp = (Date) attributes.get("timeStamp");

        if (timeStamp != null) {
            setTimeStamp(timeStamp);
        }

        Long id_caso = (Long) attributes.get("id_caso");

        if (id_caso != null) {
            setId_caso(id_caso);
        }
    }

    @Override
    public long getId_paso() {
        return _id_paso;
    }

    @Override
    public void setId_paso(long id_paso) {
        _id_paso = id_paso;
    }

    @Override
    public long getId_GPR_paso() {
        return _id_GPR_paso;
    }

    @Override
    public void setId_GPR_paso(long id_GPR_paso) {
        _id_GPR_paso = id_GPR_paso;
    }

    @Override
    public long getContent() {
        return _content;
    }

    @Override
    public void setContent(long content) {
        _content = content;
    }

    @Override
    public Date getTimeStamp() {
        return _timeStamp;
    }

    @Override
    public void setTimeStamp(Date timeStamp) {
        _timeStamp = timeStamp;
    }

    @Override
    public long getId_caso() {
        return _id_caso;
    }

    @Override
    public void setId_caso(long id_caso) {
        _id_caso = id_caso;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Paso.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Paso toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Paso) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PasoImpl pasoImpl = new PasoImpl();

        pasoImpl.setId_paso(getId_paso());
        pasoImpl.setId_GPR_paso(getId_GPR_paso());
        pasoImpl.setContent(getContent());
        pasoImpl.setTimeStamp(getTimeStamp());
        pasoImpl.setId_caso(getId_caso());

        pasoImpl.resetOriginalValues();

        return pasoImpl;
    }

    @Override
    public int compareTo(Paso paso) {
        long primaryKey = paso.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Paso)) {
            return false;
        }

        Paso paso = (Paso) obj;

        long primaryKey = paso.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Paso> toCacheModel() {
        PasoCacheModel pasoCacheModel = new PasoCacheModel();

        pasoCacheModel.id_paso = getId_paso();

        pasoCacheModel.id_GPR_paso = getId_GPR_paso();

        pasoCacheModel.content = getContent();

        Date timeStamp = getTimeStamp();

        if (timeStamp != null) {
            pasoCacheModel.timeStamp = timeStamp.getTime();
        } else {
            pasoCacheModel.timeStamp = Long.MIN_VALUE;
        }

        pasoCacheModel.id_caso = getId_caso();

        return pasoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{id_paso=");
        sb.append(getId_paso());
        sb.append(", id_GPR_paso=");
        sb.append(getId_GPR_paso());
        sb.append(", content=");
        sb.append(getContent());
        sb.append(", timeStamp=");
        sb.append(getTimeStamp());
        sb.append(", id_caso=");
        sb.append(getId_caso());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append("ec.gob.snap.vuv.model.Paso");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id_paso</column-name><column-value><![CDATA[");
        sb.append(getId_paso());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>id_GPR_paso</column-name><column-value><![CDATA[");
        sb.append(getId_GPR_paso());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>content</column-name><column-value><![CDATA[");
        sb.append(getContent());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>timeStamp</column-name><column-value><![CDATA[");
        sb.append(getTimeStamp());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>id_caso</column-name><column-value><![CDATA[");
        sb.append(getId_caso());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
