package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ec.gob.snap.vuv.model.Servicio;
import ec.gob.snap.vuv.service.ServicioLocalServiceUtil;

/**
 * The extended model base implementation for the Servicio service. Represents a row in the &quot;vuv_gpr_service_builder_Servicio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ServicioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServicioImpl
 * @see ec.gob.snap.vuv.model.Servicio
 * @generated
 */
public abstract class ServicioBaseImpl extends ServicioModelImpl
    implements Servicio {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a servicio model instance should use the {@link Servicio} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ServicioLocalServiceUtil.addServicio(this);
        } else {
            ServicioLocalServiceUtil.updateServicio(this);
        }
    }
}
