package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import ec.gob.snap.vuv.model.Servicio;
import ec.gob.snap.vuv.model.ServicioModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Servicio service. Represents a row in the &quot;vuv_gpr_service_builder_Servicio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ec.gob.snap.vuv.model.ServicioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ServicioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServicioImpl
 * @see ec.gob.snap.vuv.model.Servicio
 * @see ec.gob.snap.vuv.model.ServicioModel
 * @generated
 */
public class ServicioModelImpl extends BaseModelImpl<Servicio>
    implements ServicioModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a servicio model instance should use the {@link ec.gob.snap.vuv.model.Servicio} interface instead.
     */
    public static final String TABLE_NAME = "vuv_gpr_service_builder_Servicio";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_GPR_servicio", Types.BIGINT },
            { "content", Types.BIGINT },
            { "timeStamp", Types.TIMESTAMP },
            { "id_servicio", Types.BIGINT },
            { "id_institucion", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table vuv_gpr_service_builder_Servicio (id_GPR_servicio LONG,content LONG,timeStamp DATE null,id_servicio LONG not null primary key,id_institucion LONG)";
    public static final String TABLE_SQL_DROP = "drop table vuv_gpr_service_builder_Servicio";
    public static final String ORDER_BY_JPQL = " ORDER BY servicio.id_servicio ASC";
    public static final String ORDER_BY_SQL = " ORDER BY vuv_gpr_service_builder_Servicio.id_servicio ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.ec.gob.snap.vuv.model.Servicio"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.ec.gob.snap.vuv.model.Servicio"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.ec.gob.snap.vuv.model.Servicio"));
    private static ClassLoader _classLoader = Servicio.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Servicio.class
        };
    private long _id_GPR_servicio;
    private long _content;
    private Date _timeStamp;
    private long _id_servicio;
    private long _id_institucion;
    private Servicio _escapedModel;

    public ServicioModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _id_servicio;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId_servicio(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id_servicio;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Servicio.class;
    }

    @Override
    public String getModelClassName() {
        return Servicio.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id_GPR_servicio", getId_GPR_servicio());
        attributes.put("content", getContent());
        attributes.put("timeStamp", getTimeStamp());
        attributes.put("id_servicio", getId_servicio());
        attributes.put("id_institucion", getId_institucion());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id_GPR_servicio = (Long) attributes.get("id_GPR_servicio");

        if (id_GPR_servicio != null) {
            setId_GPR_servicio(id_GPR_servicio);
        }

        Long content = (Long) attributes.get("content");

        if (content != null) {
            setContent(content);
        }

        Date timeStamp = (Date) attributes.get("timeStamp");

        if (timeStamp != null) {
            setTimeStamp(timeStamp);
        }

        Long id_servicio = (Long) attributes.get("id_servicio");

        if (id_servicio != null) {
            setId_servicio(id_servicio);
        }

        Long id_institucion = (Long) attributes.get("id_institucion");

        if (id_institucion != null) {
            setId_institucion(id_institucion);
        }
    }

    @Override
    public long getId_GPR_servicio() {
        return _id_GPR_servicio;
    }

    @Override
    public void setId_GPR_servicio(long id_GPR_servicio) {
        _id_GPR_servicio = id_GPR_servicio;
    }

    @Override
    public long getContent() {
        return _content;
    }

    @Override
    public void setContent(long content) {
        _content = content;
    }

    @Override
    public Date getTimeStamp() {
        return _timeStamp;
    }

    @Override
    public void setTimeStamp(Date timeStamp) {
        _timeStamp = timeStamp;
    }

    @Override
    public long getId_servicio() {
        return _id_servicio;
    }

    @Override
    public void setId_servicio(long id_servicio) {
        _id_servicio = id_servicio;
    }

    @Override
    public long getId_institucion() {
        return _id_institucion;
    }

    @Override
    public void setId_institucion(long id_institucion) {
        _id_institucion = id_institucion;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Servicio.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Servicio toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Servicio) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ServicioImpl servicioImpl = new ServicioImpl();

        servicioImpl.setId_GPR_servicio(getId_GPR_servicio());
        servicioImpl.setContent(getContent());
        servicioImpl.setTimeStamp(getTimeStamp());
        servicioImpl.setId_servicio(getId_servicio());
        servicioImpl.setId_institucion(getId_institucion());

        servicioImpl.resetOriginalValues();

        return servicioImpl;
    }

    @Override
    public int compareTo(Servicio servicio) {
        long primaryKey = servicio.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Servicio)) {
            return false;
        }

        Servicio servicio = (Servicio) obj;

        long primaryKey = servicio.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Servicio> toCacheModel() {
        ServicioCacheModel servicioCacheModel = new ServicioCacheModel();

        servicioCacheModel.id_GPR_servicio = getId_GPR_servicio();

        servicioCacheModel.content = getContent();

        Date timeStamp = getTimeStamp();

        if (timeStamp != null) {
            servicioCacheModel.timeStamp = timeStamp.getTime();
        } else {
            servicioCacheModel.timeStamp = Long.MIN_VALUE;
        }

        servicioCacheModel.id_servicio = getId_servicio();

        servicioCacheModel.id_institucion = getId_institucion();

        return servicioCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{id_GPR_servicio=");
        sb.append(getId_GPR_servicio());
        sb.append(", content=");
        sb.append(getContent());
        sb.append(", timeStamp=");
        sb.append(getTimeStamp());
        sb.append(", id_servicio=");
        sb.append(getId_servicio());
        sb.append(", id_institucion=");
        sb.append(getId_institucion());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append("ec.gob.snap.vuv.model.Servicio");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id_GPR_servicio</column-name><column-value><![CDATA[");
        sb.append(getId_GPR_servicio());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>content</column-name><column-value><![CDATA[");
        sb.append(getContent());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>timeStamp</column-name><column-value><![CDATA[");
        sb.append(getTimeStamp());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>id_servicio</column-name><column-value><![CDATA[");
        sb.append(getId_servicio());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>id_institucion</column-name><column-value><![CDATA[");
        sb.append(getId_institucion());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
