/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.near.reynasa.masiveLoadUser.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MasiveLoadUser service. Represents a row in the &quot;reynasa_MasiveLoadUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.near.reynasa.masiveLoadUser.model.impl.MasiveLoadUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.near.reynasa.masiveLoadUser.model.impl.MasiveLoadUserImpl}.
 * </p>
 *
 * @author near
 * @see MasiveLoadUser
 * @see com.near.reynasa.masiveLoadUser.model.impl.MasiveLoadUserImpl
 * @see com.near.reynasa.masiveLoadUser.model.impl.MasiveLoadUserModelImpl
 * @generated
 */
public interface MasiveLoadUserModel extends BaseModel<MasiveLoadUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a masive load user model instance should use the {@link MasiveLoadUser} interface instead.
	 */

	/**
	 * Returns the primary key of this masive load user.
	 *
	 * @return the primary key of this masive load user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this masive load user.
	 *
	 * @param primaryKey the primary key of this masive load user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this masive load user.
	 *
	 * @return the ID of this masive load user
	 */
	public long getId();

	/**
	 * Sets the ID of this masive load user.
	 *
	 * @param id the ID of this masive load user
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this masive load user.
	 *
	 * @return the group ID of this masive load user
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this masive load user.
	 *
	 * @param groupId the group ID of this masive load user
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this masive load user.
	 *
	 * @return the company ID of this masive load user
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this masive load user.
	 *
	 * @param companyId the company ID of this masive load user
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this masive load user.
	 *
	 * @return the user ID of this masive load user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this masive load user.
	 *
	 * @param userId the user ID of this masive load user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this masive load user.
	 *
	 * @return the user uuid of this masive load user
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this masive load user.
	 *
	 * @param userUuid the user uuid of this masive load user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this masive load user.
	 *
	 * @return the user name of this masive load user
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this masive load user.
	 *
	 * @param userName the user name of this masive load user
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this masive load user.
	 *
	 * @return the create date of this masive load user
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this masive load user.
	 *
	 * @param createDate the create date of this masive load user
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the success file of this masive load user.
	 *
	 * @return the success file of this masive load user
	 */
	public long getSuccessFile();

	/**
	 * Sets the success file of this masive load user.
	 *
	 * @param successFile the success file of this masive load user
	 */
	public void setSuccessFile(long successFile);

	/**
	 * Returns the error file of this masive load user.
	 *
	 * @return the error file of this masive load user
	 */
	public long getErrorFile();

	/**
	 * Sets the error file of this masive load user.
	 *
	 * @param errorFile the error file of this masive load user
	 */
	public void setErrorFile(long errorFile);

	/**
	 * Returns the status execution of this masive load user.
	 *
	 * @return the status execution of this masive load user
	 */
	public int getStatusExecution();

	/**
	 * Sets the status execution of this masive load user.
	 *
	 * @param statusExecution the status execution of this masive load user
	 */
	public void setStatusExecution(int statusExecution);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MasiveLoadUser masiveLoadUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MasiveLoadUser> toCacheModel();

	@Override
	public MasiveLoadUser toEscapedModel();

	@Override
	public MasiveLoadUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}