package com.gfi.chg.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Area service. Represents a row in the &quot;chg_Area&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.gfi.chg.model.impl.AreaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.gfi.chg.model.impl.AreaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Area
 * @see com.gfi.chg.model.impl.AreaImpl
 * @see com.gfi.chg.model.impl.AreaModelImpl
 * @generated
 */
public interface AreaModel extends BaseModel<Area> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a area model instance should use the {@link Area} interface instead.
     */

    /**
     * Returns the primary key of this area.
     *
     * @return the primary key of this area
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this area.
     *
     * @param primaryKey the primary key of this area
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the area ID of this area.
     *
     * @return the area ID of this area
     */
    public long getAreaId();

    /**
     * Sets the area ID of this area.
     *
     * @param areaId the area ID of this area
     */
    public void setAreaId(long areaId);

    /**
     * Returns the name of this area.
     *
     * @return the name of this area
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this area.
     *
     * @param name the name of this area
     */
    public void setName(String name);

    /**
     * Returns the main email of this area.
     *
     * @return the main email of this area
     */
    @AutoEscape
    public String getMainEmail();

    /**
     * Sets the main email of this area.
     *
     * @param mainEmail the main email of this area
     */
    public void setMainEmail(String mainEmail);

    /**
     * Returns the user ID of this area.
     *
     * @return the user ID of this area
     */
    public long getUserId();

    /**
     * Sets the user ID of this area.
     *
     * @param userId the user ID of this area
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this area.
     *
     * @return the user uuid of this area
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this area.
     *
     * @param userUuid the user uuid of this area
     */
    public void setUserUuid(String userUuid);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.gfi.chg.model.Area area);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.gfi.chg.model.Area> toCacheModel();

    @Override
    public com.gfi.chg.model.Area toEscapedModel();

    @Override
    public com.gfi.chg.model.Area toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
