package com.gfi.chg.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Contact service. Represents a row in the &quot;chg_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.gfi.chg.model.impl.ContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.gfi.chg.model.impl.ContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Contact
 * @see com.gfi.chg.model.impl.ContactImpl
 * @see com.gfi.chg.model.impl.ContactModelImpl
 * @generated
 */
public interface ContactModel extends BaseModel<Contact> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a contact model instance should use the {@link Contact} interface instead.
     */

    /**
     * Returns the primary key of this contact.
     *
     * @return the primary key of this contact
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this contact.
     *
     * @param primaryKey the primary key of this contact
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the contact ID of this contact.
     *
     * @return the contact ID of this contact
     */
    public long getContactId();

    /**
     * Sets the contact ID of this contact.
     *
     * @param contactId the contact ID of this contact
     */
    public void setContactId(long contactId);

    /**
     * Returns the area ID of this contact.
     *
     * @return the area ID of this contact
     */
    public long getAreaId();

    /**
     * Sets the area ID of this contact.
     *
     * @param areaId the area ID of this contact
     */
    public void setAreaId(long areaId);

    /**
     * Returns the create date of this contact.
     *
     * @return the create date of this contact
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this contact.
     *
     * @param createDate the create date of this contact
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the status of this contact.
     *
     * @return the status of this contact
     */
    public int getStatus();

    /**
     * Sets the status of this contact.
     *
     * @param status the status of this contact
     */
    public void setStatus(int status);

    /**
     * Returns the name of this contact.
     *
     * @return the name of this contact
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this contact.
     *
     * @param name the name of this contact
     */
    public void setName(String name);

    /**
     * Returns the surname of this contact.
     *
     * @return the surname of this contact
     */
    @AutoEscape
    public String getSurname();

    /**
     * Sets the surname of this contact.
     *
     * @param surname the surname of this contact
     */
    public void setSurname(String surname);

    /**
     * Returns the activity of this contact.
     *
     * @return the activity of this contact
     */
    @AutoEscape
    public String getActivity();

    /**
     * Sets the activity of this contact.
     *
     * @param activity the activity of this contact
     */
    public void setActivity(String activity);

    /**
     * Returns the address of this contact.
     *
     * @return the address of this contact
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this contact.
     *
     * @param address the address of this contact
     */
    public void setAddress(String address);

    /**
     * Returns the city of this contact.
     *
     * @return the city of this contact
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this contact.
     *
     * @param city the city of this contact
     */
    public void setCity(String city);

    /**
     * Returns the postal code of this contact.
     *
     * @return the postal code of this contact
     */
    @AutoEscape
    public String getPostalCode();

    /**
     * Sets the postal code of this contact.
     *
     * @param postalCode the postal code of this contact
     */
    public void setPostalCode(String postalCode);

    /**
     * Returns the email of this contact.
     *
     * @return the email of this contact
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this contact.
     *
     * @param email the email of this contact
     */
    public void setEmail(String email);

    /**
     * Returns the telephone of this contact.
     *
     * @return the telephone of this contact
     */
    @AutoEscape
    public String getTelephone();

    /**
     * Sets the telephone of this contact.
     *
     * @param telephone the telephone of this contact
     */
    public void setTelephone(String telephone);

    /**
     * Returns the subject of this contact.
     *
     * @return the subject of this contact
     */
    @AutoEscape
    public String getSubject();

    /**
     * Sets the subject of this contact.
     *
     * @param subject the subject of this contact
     */
    public void setSubject(String subject);

    /**
     * Returns the description of this contact.
     *
     * @return the description of this contact
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this contact.
     *
     * @param description the description of this contact
     */
    public void setDescription(String description);

    /**
     * Returns the response of this contact.
     *
     * @return the response of this contact
     */
    @AutoEscape
    public String getResponse();

    /**
     * Sets the response of this contact.
     *
     * @param response the response of this contact
     */
    public void setResponse(String response);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.gfi.chg.model.Contact contact);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.gfi.chg.model.Contact> toCacheModel();

    @Override
    public com.gfi.chg.model.Contact toEscapedModel();

    @Override
    public com.gfi.chg.model.Contact toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
