package com.gfi.chg.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Tracing service. Represents a row in the &quot;chg_Tracing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.gfi.chg.model.impl.TracingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.gfi.chg.model.impl.TracingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tracing
 * @see com.gfi.chg.model.impl.TracingImpl
 * @see com.gfi.chg.model.impl.TracingModelImpl
 * @generated
 */
public interface TracingModel extends BaseModel<Tracing> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a tracing model instance should use the {@link Tracing} interface instead.
     */

    /**
     * Returns the primary key of this tracing.
     *
     * @return the primary key of this tracing
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this tracing.
     *
     * @param primaryKey the primary key of this tracing
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the tracing ID of this tracing.
     *
     * @return the tracing ID of this tracing
     */
    public long getTracingId();

    /**
     * Sets the tracing ID of this tracing.
     *
     * @param tracingId the tracing ID of this tracing
     */
    public void setTracingId(long tracingId);

    /**
     * Returns the area ID of this tracing.
     *
     * @return the area ID of this tracing
     */
    public long getAreaId();

    /**
     * Sets the area ID of this tracing.
     *
     * @param areaId the area ID of this tracing
     */
    public void setAreaId(long areaId);

    /**
     * Returns the contact ID of this tracing.
     *
     * @return the contact ID of this tracing
     */
    public long getContactId();

    /**
     * Sets the contact ID of this tracing.
     *
     * @param contactId the contact ID of this tracing
     */
    public void setContactId(long contactId);

    /**
     * Returns the status of this tracing.
     *
     * @return the status of this tracing
     */
    public int getStatus();

    /**
     * Sets the status of this tracing.
     *
     * @param status the status of this tracing
     */
    public void setStatus(int status);

    /**
     * Returns the modified date of this tracing.
     *
     * @return the modified date of this tracing
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this tracing.
     *
     * @param modifiedDate the modified date of this tracing
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the comment of this tracing.
     *
     * @return the comment of this tracing
     */
    @AutoEscape
    public String getComment();

    /**
     * Sets the comment of this tracing.
     *
     * @param comment the comment of this tracing
     */
    public void setComment(String comment);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.gfi.chg.model.Tracing tracing);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.gfi.chg.model.Tracing> toCacheModel();

    @Override
    public com.gfi.chg.model.Tracing toEscapedModel();

    @Override
    public com.gfi.chg.model.Tracing toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
