package com.gfi.chg.model.impl;

import com.gfi.chg.model.Tracing;
import com.gfi.chg.service.TracingLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Tracing service. Represents a row in the &quot;chg_Tracing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TracingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TracingImpl
 * @see com.gfi.chg.model.Tracing
 * @generated
 */
public abstract class TracingBaseImpl extends TracingModelImpl
    implements Tracing {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a tracing model instance should use the {@link Tracing} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TracingLocalServiceUtil.addTracing(this);
        } else {
            TracingLocalServiceUtil.updateTracing(this);
        }
    }
}
