package ec.gob.snap.vuv.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Paso service. Represents a row in the &quot;vuv_gpr_service_builder_Paso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.gob.snap.vuv.model.impl.PasoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.gob.snap.vuv.model.impl.PasoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Paso
 * @see ec.gob.snap.vuv.model.impl.PasoImpl
 * @see ec.gob.snap.vuv.model.impl.PasoModelImpl
 * @generated
 */
public interface PasoModel extends BaseModel<Paso> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a paso model instance should use the {@link Paso} interface instead.
     */

    /**
     * Returns the primary key of this paso.
     *
     * @return the primary key of this paso
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this paso.
     *
     * @param primaryKey the primary key of this paso
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id_paso of this paso.
     *
     * @return the id_paso of this paso
     */
    public long getId_paso();

    /**
     * Sets the id_paso of this paso.
     *
     * @param id_paso the id_paso of this paso
     */
    public void setId_paso(long id_paso);

    /**
     * Returns the id_ g p r_paso of this paso.
     *
     * @return the id_ g p r_paso of this paso
     */
    public long getId_GPR_paso();

    /**
     * Sets the id_ g p r_paso of this paso.
     *
     * @param id_GPR_paso the id_ g p r_paso of this paso
     */
    public void setId_GPR_paso(long id_GPR_paso);

    /**
     * Returns the content of this paso.
     *
     * @return the content of this paso
     */
    public long getContent();

    /**
     * Sets the content of this paso.
     *
     * @param content the content of this paso
     */
    public void setContent(long content);

    /**
     * Returns the time stamp of this paso.
     *
     * @return the time stamp of this paso
     */
    public Date getTimeStamp();

    /**
     * Sets the time stamp of this paso.
     *
     * @param timeStamp the time stamp of this paso
     */
    public void setTimeStamp(Date timeStamp);

    /**
     * Returns the id_caso of this paso.
     *
     * @return the id_caso of this paso
     */
    public long getId_caso();

    /**
     * Sets the id_caso of this paso.
     *
     * @param id_caso the id_caso of this paso
     */
    public void setId_caso(long id_caso);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Paso paso);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Paso> toCacheModel();

    @Override
    public Paso toEscapedModel();

    @Override
    public Paso toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
