package ec.gob.snap.vuv.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Servicio service. Represents a row in the &quot;vuv_gpr_service_builder_Servicio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.gob.snap.vuv.model.impl.ServicioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.gob.snap.vuv.model.impl.ServicioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Servicio
 * @see ec.gob.snap.vuv.model.impl.ServicioImpl
 * @see ec.gob.snap.vuv.model.impl.ServicioModelImpl
 * @generated
 */
public interface ServicioModel extends BaseModel<Servicio> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a servicio model instance should use the {@link Servicio} interface instead.
     */

    /**
     * Returns the primary key of this servicio.
     *
     * @return the primary key of this servicio
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this servicio.
     *
     * @param primaryKey the primary key of this servicio
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id_ g p r_servicio of this servicio.
     *
     * @return the id_ g p r_servicio of this servicio
     */
    public long getId_GPR_servicio();

    /**
     * Sets the id_ g p r_servicio of this servicio.
     *
     * @param id_GPR_servicio the id_ g p r_servicio of this servicio
     */
    public void setId_GPR_servicio(long id_GPR_servicio);

    /**
     * Returns the content of this servicio.
     *
     * @return the content of this servicio
     */
    public long getContent();

    /**
     * Sets the content of this servicio.
     *
     * @param content the content of this servicio
     */
    public void setContent(long content);

    /**
     * Returns the time stamp of this servicio.
     *
     * @return the time stamp of this servicio
     */
    public Date getTimeStamp();

    /**
     * Sets the time stamp of this servicio.
     *
     * @param timeStamp the time stamp of this servicio
     */
    public void setTimeStamp(Date timeStamp);

    /**
     * Returns the id_servicio of this servicio.
     *
     * @return the id_servicio of this servicio
     */
    public long getId_servicio();

    /**
     * Sets the id_servicio of this servicio.
     *
     * @param id_servicio the id_servicio of this servicio
     */
    public void setId_servicio(long id_servicio);

    /**
     * Returns the id_institucion of this servicio.
     *
     * @return the id_institucion of this servicio
     */
    public long getId_institucion();

    /**
     * Sets the id_institucion of this servicio.
     *
     * @param id_institucion the id_institucion of this servicio
     */
    public void setId_institucion(long id_institucion);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Servicio servicio);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Servicio> toCacheModel();

    @Override
    public Servicio toEscapedModel();

    @Override
    public Servicio toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
