//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 08:24:32 AM CEST 
//


package ec.gob.snap.vuv.dynamic.form.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for properties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="properties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="label">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="es" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="en" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="qu" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="accion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{}tipo"/>
 *         &lt;element name="fieldRequired" type="{}tipoBoolean"/>
 *         &lt;element name="readOnly" type="{}tipoBoolean"/>
 *         &lt;element name="groupWithPrevious" type="{}tipoBoolean"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="onChangeScript" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="es" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="en" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="qu" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "properties", propOrder = {
    "labelOrAccionOrValue"
})
public class Properties {

    @XmlElementRefs({
        @XmlElementRef(name = "onChangeScript", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "maxLength", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "label", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "value", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "groupWithPrevious", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "size", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "readOnly", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "accion", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "height", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fieldRequired", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "title", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> labelOrAccionOrValue;

    /**
     * Gets the value of the labelOrAccionOrValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelOrAccionOrValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelOrAccionOrValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Properties.Label }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TipoBoolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TipoBoolean }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Tipo }{@code >}
     * {@link JAXBElement }{@code <}{@link TipoBoolean }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Properties.Title }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getLabelOrAccionOrValue() {
        if (labelOrAccionOrValue == null) {
            labelOrAccionOrValue = new ArrayList<JAXBElement<?>>();
        }
        return this.labelOrAccionOrValue;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="es" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="en" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="qu" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "es",
        "en",
        "qu"
    })
    public static class Label {

        @XmlElement(required = true)
        protected Object es;
        @XmlElement(required = true)
        protected Object en;
        @XmlElement(required = true)
        protected Object qu;

        /**
         * Gets the value of the es property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEs() {
            return es;
        }

        /**
         * Sets the value of the es property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEs(Object value) {
            this.es = value;
        }

        /**
         * Gets the value of the en property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEn() {
            return en;
        }

        /**
         * Sets the value of the en property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEn(Object value) {
            this.en = value;
        }

        /**
         * Gets the value of the qu property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getQu() {
            return qu;
        }

        /**
         * Sets the value of the qu property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setQu(Object value) {
            this.qu = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="es" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="en" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="qu" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "es",
        "en",
        "qu"
    })
    public static class Title {

        @XmlElement(required = true)
        protected Object es;
        @XmlElement(required = true)
        protected Object en;
        @XmlElement(required = true)
        protected Object qu;

        /**
         * Gets the value of the es property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEs() {
            return es;
        }

        /**
         * Sets the value of the es property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEs(Object value) {
            this.es = value;
        }

        /**
         * Gets the value of the en property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEn() {
            return en;
        }

        /**
         * Sets the value of the en property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEn(Object value) {
            this.en = value;
        }

        /**
         * Gets the value of the qu property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getQu() {
            return qu;
        }

        /**
         * Sets the value of the qu property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setQu(Object value) {
            this.qu = value;
        }

    }

}
