/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.near.reynasa.masiveLoadUser.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.near.reynasa.masiveLoadUser.model.MasiveLoadUser;
import com.near.reynasa.masiveLoadUser.service.MasiveLoadUserLocalServiceUtil;

/**
 * The extended model base implementation for the MasiveLoadUser service. Represents a row in the &quot;reynasa_MasiveLoadUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasiveLoadUserImpl}.
 * </p>
 *
 * @author near
 * @see MasiveLoadUserImpl
 * @see com.near.reynasa.masiveLoadUser.model.MasiveLoadUser
 * @generated
 */
public abstract class MasiveLoadUserBaseImpl extends MasiveLoadUserModelImpl
	implements MasiveLoadUser {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a masive load user model instance should use the {@link MasiveLoadUser} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			MasiveLoadUserLocalServiceUtil.addMasiveLoadUser(this);
		}
		else {
			MasiveLoadUserLocalServiceUtil.updateMasiveLoadUser(this);
		}
	}
}