package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ec.gob.snap.vuv.model.Caso;
import ec.gob.snap.vuv.service.CasoLocalServiceUtil;

/**
 * The extended model base implementation for the Caso service. Represents a row in the &quot;vuv_gpr_service_builder_Caso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CasoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CasoImpl
 * @see ec.gob.snap.vuv.model.Caso
 * @generated
 */
public abstract class CasoBaseImpl extends CasoModelImpl implements Caso {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a caso model instance should use the {@link Caso} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CasoLocalServiceUtil.addCaso(this);
        } else {
            CasoLocalServiceUtil.updateCaso(this);
        }
    }
}
