package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ec.gob.snap.vuv.model.Indicador;
import ec.gob.snap.vuv.service.IndicadorLocalServiceUtil;

/**
 * The extended model base implementation for the Indicador service. Represents a row in the &quot;vuv_gpr_service_builder_Indicador&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IndicadorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IndicadorImpl
 * @see ec.gob.snap.vuv.model.Indicador
 * @generated
 */
public abstract class IndicadorBaseImpl extends IndicadorModelImpl
    implements Indicador {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a indicador model instance should use the {@link Indicador} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            IndicadorLocalServiceUtil.addIndicador(this);
        } else {
            IndicadorLocalServiceUtil.updateIndicador(this);
        }
    }
}
