package ec.gob.snap.vuv.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ec.gob.snap.vuv.model.Paso;
import ec.gob.snap.vuv.service.PasoLocalServiceUtil;

/**
 * The extended model base implementation for the Paso service. Represents a row in the &quot;vuv_gpr_service_builder_Paso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PasoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PasoImpl
 * @see ec.gob.snap.vuv.model.Paso
 * @generated
 */
public abstract class PasoBaseImpl extends PasoModelImpl implements Paso {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a paso model instance should use the {@link Paso} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PasoLocalServiceUtil.addPaso(this);
        } else {
            PasoLocalServiceUtil.updatePaso(this);
        }
    }
}
