package ec.gob.snap.vuv.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Act_Institucional service. Represents a row in the &quot;vuv_gpr_service_builder_Act_Institucional&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.gob.snap.vuv.model.impl.Act_InstitucionalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.gob.snap.vuv.model.impl.Act_InstitucionalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Act_Institucional
 * @see ec.gob.snap.vuv.model.impl.Act_InstitucionalImpl
 * @see ec.gob.snap.vuv.model.impl.Act_InstitucionalModelImpl
 * @generated
 */
public interface Act_InstitucionalModel extends BaseModel<Act_Institucional> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a act_ institucional model instance should use the {@link Act_Institucional} interface instead.
     */

    /**
     * Returns the primary key of this act_ institucional.
     *
     * @return the primary key of this act_ institucional
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this act_ institucional.
     *
     * @param primaryKey the primary key of this act_ institucional
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id_act_institucional of this act_ institucional.
     *
     * @return the id_act_institucional of this act_ institucional
     */
    public long getId_act_institucional();

    /**
     * Sets the id_act_institucional of this act_ institucional.
     *
     * @param id_act_institucional the id_act_institucional of this act_ institucional
     */
    public void setId_act_institucional(long id_act_institucional);

    /**
     * Returns the id_ g p r_act_institucional of this act_ institucional.
     *
     * @return the id_ g p r_act_institucional of this act_ institucional
     */
    public long getId_GPR_act_institucional();

    /**
     * Sets the id_ g p r_act_institucional of this act_ institucional.
     *
     * @param id_GPR_act_institucional the id_ g p r_act_institucional of this act_ institucional
     */
    public void setId_GPR_act_institucional(long id_GPR_act_institucional);

    /**
     * Returns the content of this act_ institucional.
     *
     * @return the content of this act_ institucional
     */
    public long getContent();

    /**
     * Sets the content of this act_ institucional.
     *
     * @param content the content of this act_ institucional
     */
    public void setContent(long content);

    /**
     * Returns the time stamp of this act_ institucional.
     *
     * @return the time stamp of this act_ institucional
     */
    public Date getTimeStamp();

    /**
     * Sets the time stamp of this act_ institucional.
     *
     * @param timeStamp the time stamp of this act_ institucional
     */
    public void setTimeStamp(Date timeStamp);

    /**
     * Returns the id_servicio of this act_ institucional.
     *
     * @return the id_servicio of this act_ institucional
     */
    public long getId_servicio();

    /**
     * Sets the id_servicio of this act_ institucional.
     *
     * @param id_servicio the id_servicio of this act_ institucional
     */
    public void setId_servicio(long id_servicio);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Act_Institucional act_Institucional);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Act_Institucional> toCacheModel();

    @Override
    public Act_Institucional toEscapedModel();

    @Override
    public Act_Institucional toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
