package ec.gob.snap.vuv.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Caso service. Represents a row in the &quot;vuv_gpr_service_builder_Caso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.gob.snap.vuv.model.impl.CasoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.gob.snap.vuv.model.impl.CasoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Caso
 * @see ec.gob.snap.vuv.model.impl.CasoImpl
 * @see ec.gob.snap.vuv.model.impl.CasoModelImpl
 * @generated
 */
public interface CasoModel extends BaseModel<Caso> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a caso model instance should use the {@link Caso} interface instead.
     */

    /**
     * Returns the primary key of this caso.
     *
     * @return the primary key of this caso
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this caso.
     *
     * @param primaryKey the primary key of this caso
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id_caso of this caso.
     *
     * @return the id_caso of this caso
     */
    public long getId_caso();

    /**
     * Sets the id_caso of this caso.
     *
     * @param id_caso the id_caso of this caso
     */
    public void setId_caso(long id_caso);

    /**
     * Returns the id_ g p r_caso of this caso.
     *
     * @return the id_ g p r_caso of this caso
     */
    public long getId_GPR_caso();

    /**
     * Sets the id_ g p r_caso of this caso.
     *
     * @param id_GPR_caso the id_ g p r_caso of this caso
     */
    public void setId_GPR_caso(long id_GPR_caso);

    /**
     * Returns the content of this caso.
     *
     * @return the content of this caso
     */
    public long getContent();

    /**
     * Sets the content of this caso.
     *
     * @param content the content of this caso
     */
    public void setContent(long content);

    /**
     * Returns the time stamp of this caso.
     *
     * @return the time stamp of this caso
     */
    public Date getTimeStamp();

    /**
     * Sets the time stamp of this caso.
     *
     * @param timeStamp the time stamp of this caso
     */
    public void setTimeStamp(Date timeStamp);

    /**
     * Returns the id_servicio of this caso.
     *
     * @return the id_servicio of this caso
     */
    public long getId_servicio();

    /**
     * Sets the id_servicio of this caso.
     *
     * @param id_servicio the id_servicio of this caso
     */
    public void setId_servicio(long id_servicio);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Caso caso);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Caso> toCacheModel();

    @Override
    public Caso toEscapedModel();

    @Override
    public Caso toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
