package ec.gob.snap.vuv.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Centro service. Represents a row in the &quot;vuv_gpr_service_builder_Centro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.gob.snap.vuv.model.impl.CentroModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.gob.snap.vuv.model.impl.CentroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Centro
 * @see ec.gob.snap.vuv.model.impl.CentroImpl
 * @see ec.gob.snap.vuv.model.impl.CentroModelImpl
 * @generated
 */
public interface CentroModel extends BaseModel<Centro> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a centro model instance should use the {@link Centro} interface instead.
     */

    /**
     * Returns the primary key of this centro.
     *
     * @return the primary key of this centro
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this centro.
     *
     * @param primaryKey the primary key of this centro
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id_centro of this centro.
     *
     * @return the id_centro of this centro
     */
    public long getId_centro();

    /**
     * Sets the id_centro of this centro.
     *
     * @param id_centro the id_centro of this centro
     */
    public void setId_centro(long id_centro);

    /**
     * Returns the id_ g p r_centro of this centro.
     *
     * @return the id_ g p r_centro of this centro
     */
    public long getId_GPR_centro();

    /**
     * Sets the id_ g p r_centro of this centro.
     *
     * @param id_GPR_centro the id_ g p r_centro of this centro
     */
    public void setId_GPR_centro(long id_GPR_centro);

    /**
     * Returns the content of this centro.
     *
     * @return the content of this centro
     */
    public long getContent();

    /**
     * Sets the content of this centro.
     *
     * @param content the content of this centro
     */
    public void setContent(long content);

    /**
     * Returns the time stamp of this centro.
     *
     * @return the time stamp of this centro
     */
    public Date getTimeStamp();

    /**
     * Sets the time stamp of this centro.
     *
     * @param timeStamp the time stamp of this centro
     */
    public void setTimeStamp(Date timeStamp);

    /**
     * Returns the id_caso of this centro.
     *
     * @return the id_caso of this centro
     */
    public long getId_caso();

    /**
     * Sets the id_caso of this centro.
     *
     * @param id_caso the id_caso of this centro
     */
    public void setId_caso(long id_caso);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Centro centro);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Centro> toCacheModel();

    @Override
    public Centro toEscapedModel();

    @Override
    public Centro toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
