package ec.gob.snap.vuv.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Indicador service. Represents a row in the &quot;vuv_gpr_service_builder_Indicador&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.gob.snap.vuv.model.impl.IndicadorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.gob.snap.vuv.model.impl.IndicadorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Indicador
 * @see ec.gob.snap.vuv.model.impl.IndicadorImpl
 * @see ec.gob.snap.vuv.model.impl.IndicadorModelImpl
 * @generated
 */
public interface IndicadorModel extends BaseModel<Indicador> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a indicador model instance should use the {@link Indicador} interface instead.
     */

    /**
     * Returns the primary key of this indicador.
     *
     * @return the primary key of this indicador
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this indicador.
     *
     * @param primaryKey the primary key of this indicador
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id_indicador of this indicador.
     *
     * @return the id_indicador of this indicador
     */
    public long getId_indicador();

    /**
     * Sets the id_indicador of this indicador.
     *
     * @param id_indicador the id_indicador of this indicador
     */
    public void setId_indicador(long id_indicador);

    /**
     * Returns the id_ g p r_indicador of this indicador.
     *
     * @return the id_ g p r_indicador of this indicador
     */
    public long getId_GPR_indicador();

    /**
     * Sets the id_ g p r_indicador of this indicador.
     *
     * @param id_GPR_indicador the id_ g p r_indicador of this indicador
     */
    public void setId_GPR_indicador(long id_GPR_indicador);

    /**
     * Returns the content of this indicador.
     *
     * @return the content of this indicador
     */
    public long getContent();

    /**
     * Sets the content of this indicador.
     *
     * @param content the content of this indicador
     */
    public void setContent(long content);

    /**
     * Returns the time stamp of this indicador.
     *
     * @return the time stamp of this indicador
     */
    public Date getTimeStamp();

    /**
     * Sets the time stamp of this indicador.
     *
     * @param timeStamp the time stamp of this indicador
     */
    public void setTimeStamp(Date timeStamp);

    /**
     * Returns the id_servicio of this indicador.
     *
     * @return the id_servicio of this indicador
     */
    public long getId_servicio();

    /**
     * Sets the id_servicio of this indicador.
     *
     * @param id_servicio the id_servicio of this indicador
     */
    public void setId_servicio(long id_servicio);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Indicador indicador);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Indicador> toCacheModel();

    @Override
    public Indicador toEscapedModel();

    @Override
    public Indicador toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
