package ec.gob.snap.vuv.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Institucion service. Represents a row in the &quot;vuv_gpr_service_builder_Institucion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.gob.snap.vuv.model.impl.InstitucionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.gob.snap.vuv.model.impl.InstitucionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Institucion
 * @see ec.gob.snap.vuv.model.impl.InstitucionImpl
 * @see ec.gob.snap.vuv.model.impl.InstitucionModelImpl
 * @generated
 */
public interface InstitucionModel extends BaseModel<Institucion> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a institucion model instance should use the {@link Institucion} interface instead.
     */

    /**
     * Returns the primary key of this institucion.
     *
     * @return the primary key of this institucion
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this institucion.
     *
     * @param primaryKey the primary key of this institucion
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id_institucion of this institucion.
     *
     * @return the id_institucion of this institucion
     */
    public long getId_institucion();

    /**
     * Sets the id_institucion of this institucion.
     *
     * @param id_institucion the id_institucion of this institucion
     */
    public void setId_institucion(long id_institucion);

    /**
     * Returns the id_ g p r_institucion of this institucion.
     *
     * @return the id_ g p r_institucion of this institucion
     */
    public long getId_GPR_institucion();

    /**
     * Sets the id_ g p r_institucion of this institucion.
     *
     * @param id_GPR_institucion the id_ g p r_institucion of this institucion
     */
    public void setId_GPR_institucion(long id_GPR_institucion);

    /**
     * Returns the content of this institucion.
     *
     * @return the content of this institucion
     */
    public long getContent();

    /**
     * Sets the content of this institucion.
     *
     * @param content the content of this institucion
     */
    public void setContent(long content);

    /**
     * Returns the time stamp of this institucion.
     *
     * @return the time stamp of this institucion
     */
    public Date getTimeStamp();

    /**
     * Sets the time stamp of this institucion.
     *
     * @param timeStamp the time stamp of this institucion
     */
    public void setTimeStamp(Date timeStamp);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Institucion institucion);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Institucion> toCacheModel();

    @Override
    public Institucion toEscapedModel();

    @Override
    public Institucion toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
