package ec.gob.snap.vuv.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Requisito service. Represents a row in the &quot;vuv_gpr_service_builder_Requisito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.gob.snap.vuv.model.impl.RequisitoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.gob.snap.vuv.model.impl.RequisitoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Requisito
 * @see ec.gob.snap.vuv.model.impl.RequisitoImpl
 * @see ec.gob.snap.vuv.model.impl.RequisitoModelImpl
 * @generated
 */
public interface RequisitoModel extends BaseModel<Requisito> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a requisito model instance should use the {@link Requisito} interface instead.
     */

    /**
     * Returns the primary key of this requisito.
     *
     * @return the primary key of this requisito
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this requisito.
     *
     * @param primaryKey the primary key of this requisito
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id_requisito of this requisito.
     *
     * @return the id_requisito of this requisito
     */
    public long getId_requisito();

    /**
     * Sets the id_requisito of this requisito.
     *
     * @param id_requisito the id_requisito of this requisito
     */
    public void setId_requisito(long id_requisito);

    /**
     * Returns the id_ g p r_requisito of this requisito.
     *
     * @return the id_ g p r_requisito of this requisito
     */
    public long getId_GPR_requisito();

    /**
     * Sets the id_ g p r_requisito of this requisito.
     *
     * @param id_GPR_requisito the id_ g p r_requisito of this requisito
     */
    public void setId_GPR_requisito(long id_GPR_requisito);

    /**
     * Returns the content of this requisito.
     *
     * @return the content of this requisito
     */
    public long getContent();

    /**
     * Sets the content of this requisito.
     *
     * @param content the content of this requisito
     */
    public void setContent(long content);

    /**
     * Returns the time stamp of this requisito.
     *
     * @return the time stamp of this requisito
     */
    public Date getTimeStamp();

    /**
     * Sets the time stamp of this requisito.
     *
     * @param timeStamp the time stamp of this requisito
     */
    public void setTimeStamp(Date timeStamp);

    /**
     * Returns the id_paso of this requisito.
     *
     * @return the id_paso of this requisito
     */
    public long getId_paso();

    /**
     * Sets the id_paso of this requisito.
     *
     * @param id_paso the id_paso of this requisito
     */
    public void setId_paso(long id_paso);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Requisito requisito);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Requisito> toCacheModel();

    @Override
    public Requisito toEscapedModel();

    @Override
    public Requisito toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
